// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  window.ridiculoader = function(options) {
    var addSmokescreen, extend, init, removeSmokescreen, settings;
    settings = {
      gif: 'mj',
      overlayColor: 'black'
    };
    extend = function(def, config) {
      var setting, value, _results;
      _results = [];
      for (setting in config) {
        if (!__hasProp.call(config, setting)) continue;
        value = config[setting];
        _results.push(def[setting] = value);
      }
      return _results;
    };
    init = function() {
      extend(settings, options);
      addSmokescreen("ridiculoader-smokescreen");
      return removeSmokescreen();
    };
    addSmokescreen = function(id) {
      var loadingGif, modal;
      modal = document.createElement("div");
      modal.setAttribute("id", id);
      loadingGif = document.createElement("img");
      loadingGif.setAttribute("src", "img/moonwalker.gif");
      modal.style.position = 'fixed';
      modal.style.top = 0;
      modal.style.left = 0;
      modal.style.background = settings.overlayColor;
      modal.style.zIndex = 5;
      modal.style.width = '100%';
      modal.style.height = '100%';
      loadingGif.style.position = 'absolute';
      loadingGif.style.top = 0;
      loadingGif.style.bottom = 0;
      loadingGif.style.left = 0;
      loadingGif.style.right = 0;
      loadingGif.style.margin = 'auto';
      loadingGif.style.zIndex = 10;
      modal.appendChild(loadingGif);
      return document.body.appendChild(modal);
    };
    removeSmokescreen = function(id) {
      return document.getElementById(id);
    };
    return init();
  };

}).call(this);
